apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-config
data:
  DEFAULT_CITY: {{ .Values.config.defaultCity | quote }}
  DEFAULT_LANG: {{ .Values.config.defaultLang | quote }}
  APP_PORT: {{ .Values.config.appPort | quote }}